#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┏┓┏┓┏┓┏┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣ ┃┃┃┃ ┃ 
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┻ ┗┛┗┛ ┻ 
#                             


# -*- conf -*-
# Matugen

[colors-dark]
alpha=0.8
background=19120c
foreground=eee0d5
regular0=19120c
regular1=ffb4ab
regular2=fbb974
regular3=becc9b
regular4=ffdcbc
regular5=feddbe
regular6=e1c1a3
regular7=eee0d5
bright0=403830
bright1=ffb4ab
bright2=fbb974
bright3=becc9b
bright4=ffdcbc
bright5=feddbe
bright6=e1c1a3
bright7=eee0d5
dim0=45475A 
dim1=F38BA8 
dim2=A6E3A1 
dim3=F9E2AF 
dim4=89B4FA 
dim5=F5C2E7 
dim6=94E2D5 
dim7=BAC2DE 
selection-foreground=fbb974
selection-background=492900
cursor=50453a eee0d5
