#! /bin/sh


export _JAVA_AWT_WM_NONREPARENTING=1
pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr | grep -w connected | wc -l ) -eq 2 ]]; then
    xrandr --ouput eDP --primary --mode 1920x1080 --rotate normal --ouput HDMI-A-0 --mode 1024x768 --rotate normal --right-of eDP
fi

bspc monitor eDP -d 1 2 3 4 5
# bspc monitor HDMI-A-0 -d 7 8 9

bspc config border_width         2
bspc config window_gap          12
bspc config -m HDMI-A-0 window_gap 0
bspc config -m HDMI-A-0 top_padding 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a MEGAsync state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

nitrogen --restore &
~/.config/polybar/launch.sh &
picom &
nm-applet &
megasync &
blueman-applet &
emacs --daemon &
xsetroot -cursor_name left_ptr

