#+title: Polybar configuration
#+author: Soumava Seal

* What is Polybar ?

    Polybar is a fast, minimal and easy to use tool to create status bars.It is very easy to customize, enable a wide range of (editable) functionality using various modules. Polybar is especially useful for window managers that have a limited or non-existent status bar, such as awesome or i3. Polybar can also be used with desktop environments like Plasma.

    You can read more about polybar [[https://github.com/polybar/polybar][here]] and [[https://wiki.archlinux.org/title/Polybar][here]].


* Installation :

    Polybar is available in the official repositaries for most of the major distribution. You can install it using respective package manager. You can follow the instructions [[https://github.com/polybar/polybar#installation][here]].


* About My Configuration :

    This is my personal configuration for polybar. You can always clone this repository and use in your polybar config.

** Installation :

    You can install this configuration using this very simple install script. The install script is described below.

*** Take a Backup of the current config :

	#+begin_src bash :tangle install.sh

	#!/usr/bin/env bash

	if [ -d ~/.config/polybar/ ]; then
	    mkdir -p ~/.config/polybar/polybar_backup
	    mv ~/.config/polybar/* ~/.config/polybar/polybar_backup
	else
	    mkdir -p ~/.config/polybar
	fi


	#+end_src

*** Move these Config files :

	#+begin_src bash :tangle install.sh

	mv launch.sh config.ini modules.ini colors.ini ~/.config/polybar/

	#+end_src




* My Configuration :

** Sourcing different files :

    I tried to keep my config file as less cluttered as possible so I Created different files for different sections.

#+begin_src  conf
    include-file = /home/soumava/.config/polybar/colors.ini
    include-file = /home/soumava/.config/polybar/modules.ini
#+end_src


** Color Scheme :

    You can add different colors to your polybar. I personally like the gruvbox colorscheme, So my polybar colors are also inspired by the gruvbox theme.

    #+begin_src conf
        [colors]
        background = #cd2e3840
        background-alt = #444
        foreground = #ebdbb2
        background-empty = #928374
        foreground-alt = #555
        primary = #ffb52a
        secondary = #e60053
        alert = #bd2c40
    #+end_src


** Fonts :

    You can define multiple fonts in your polybar config. The fonts are defined and caled in a indexed manner. It is worth to note that the index starts from 0 at the time of defining but when we call them the numbers starts from 1.

    #+begin_src conf
        font-0 = "Dejavu Sans:style=Bold:size=10;3"
        font-1 = "Iosevka Nerd Font:style=Bold:size=15;3"
        font-2 = "Weather Icons:style=regular:size=15;3"
    #+end_src
    

** Main bar config

I have a dual monitor setup. So I configured two polybar instances for the two monitors. Below is my config for the main monitor.

#+begin_src conf :tangle newConfig.ini

[bar/mybar]
monitor = eDP
width = 95%
height = 40
offset-x = 2%
offset-y = 1%
radius = 20.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

padding = 1

module-margin-left = 1
module-margin-right = 2

modules-left = logo bspwm
modules-center = date mpd
modules-right = wlan separator battery separator pulseaudio separator cpu separator memory separator power-menu

tray-position = right
tray-padding = 2
;tray-background = #0063ff

wm-restack = bspwm

;override-redirect = true

;scroll-up = bspwm-desknext
;scroll-down = bspwm-deskprev

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev

cursor-click = pointer
cursor-scroll = ns-resize

#+end_src


** External Bar config

#+begin_src conf

[bar/external_polybar]
monitor = HDMI-A-0
width = 100%
height = 30
;offset-x = 2%
offset-y = 0%
;radius = 20.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

padding = 1

module-margin-left = 1
module-margin-right = 2

modules-left = bspwm
modules-center = date mpd
modules-right = power-menu

tray-position = right
tray-padding = 2
;tray-background = #0063ff

wm-restack = bspwm

;override-redirect = true

;scroll-up = bspwm-desknext
;scroll-down = bspwm-deskprev

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev

cursor-click = pointer
cursor-scroll = ns-resize


#+end_src


** Modules :

    I don't like to have a bunch of modules. I have a very limited number of modules in my polybar.

*** bspwm

    This the workspace manager for bspwm window manager. This is an inbuilt module in polybar though there are some customization options like the icons in each workspaces, number of workspaces font etc. You can set up the no of workspace in each screen in your bspwm config using src_conf{bspc monitor {monitor_name} -d 1 2 3 4 5} command.


    #+begin_src conf

        [module/bspwm]
        type = internal/bspwm

        enable-click = true
        enable-scroll = true
        reverse-scroll = true
        pin-workspaces = true

        ws-icon-0 = 1;
        ws-icon-1 = 2;
        ws-icon-2 = 3;
        ws-icon-3 = 4;
        ws-icon-4 = 5;
        ws-icon-5 = 6;
        ws-icon-6 = 7;
        ws-icon-7 = 8;
        ws-icon-8 = 9;
        js-icon-9 = 10;
        ws-icon-default = " "


        format = <label-state> <label-mode>

        label-focused = %icon%
        label-focused-background = ${colors.background}
        label-focused-underline= #6790eb
        label-focused-padding = 2
        label-focused-foreground = ${colors.foreground}

        label-occupied = %icon%
        label-occupied-padding = 2
        label-occupied-background = ${colors.background}

        label-urgent = %icon%
        label-urgent-padding = 2

        label-empty = %icon%
        label-empty-foreground = ${colors.background-empty}
        label-empty-padding = 2
        label-empty-background = ${colors.background}

        ; Separator in between workspaces
        ;label-separator = |
        ;label-separator-padding = 10
        ;label-separator-foreground = #ffb52a

        label-focused-font = 2
        label-empty-font = 2
        label-ocupied-font = 2

        format-foreground = ${colors.foreground}
        format-background = ${colors.background}

    #+end_src


*** date:

    #+begin_src conf

        [module/date]
        type = internal/date
        interval = 5
        date = "%d %b' %Y"
        date-alt = " %Y-%m-%d"
        time = %H:%M
        time-alt = %H:%M:%S
        label = "%time%    %date%"
        label-font = 1

    #+end_src


*** wlan:
    This is the module for network speed.

    #+begin_src conf

        [module/wlan]
        type = internal/network
        interface = wlp4s0
        ; Seconds to sleep between updates
        ; Default: 1
        interval = 1.0

        ; Test connectivity every Nth update
        ; A value of 0 disables the feature
        ; NOTE: Experimental (needs more testing)
        ; Default: 0
        ;ping-interval = 3

        ; Accumulate values from all interfaces
        ; when querying for up/downspeed rate
        ; Default: false
        accumulate-stats = true

        ; Consider an `UNKNOWN` interface state as up.
        ; Some devices like USB network adapters have
        ; an unknown state, even when they're running
        ; Default: false
        unknown-as-up = true

        ; Available tags:
        ;   <label-connected> (default)
        ;   <ramp-signal>
        format-connected = <label-connected>

        ; Available tags:
        ;   <label-disconnected> (default)
        format-disconnected =

        ; Available tags:
        ;   <label-connected> (default)
        ;   <label-packetloss>
        ;   <animation-packetloss>
        format-packetloss = <animation-packetloss> <label-connected>

        ; All labels support the following tokens:
        ;   %ifname%    [wireless+wired]
        ;   %local_ip%  [wireless+wired]
        ;   %local_ip6% [wireless+wired]
        ;   %essid%     [wireless]
        ;   %signal%    [wireless]
        ;   %upspeed%   [wireless+wired]
        ;   %downspeed% [wireless+wired]
        ;   %linkspeed% [wired]

        ; Default: %ifname% %local_ip%
        label-connected =   %upspeed%  %downspeed%
        label-connected-font = 1
        ;label-connected-foreground = #e69ea7

        ; Default: (none)
        label-disconnected = not connected
        label-disconnected-foreground = #66ffffff

        ; Default: (none)
        label-packetloss = %local_ip%
        ;label-packetloss-foreground = #eefafafa

        ; Only applies if <ramp-signal> is used
        ;ramp-signal-0 = 😱
        ;ramp-signal-1 = 😠
        ;ramp-signal-2 = 😒
        ;ramp-signal-3 = 😊
        ;ramp-signal-4 = 😃
        ;ramp-signal-5 = 😈

        ; Only applies if <animation-packetloss> is used
        ;animation-packetloss-0 =%{F#ff217c}%{F-}
        ;animation-packetloss-0-foreground = #ffa64c
        ;animation-packetloss-1 =%{F#ff217c}%{F-}
        ;animation-packetloss-1-foreground = #000000
        ; Framerate in milliseconds
        ;animation-packetloss-framerate = 500

    #+end_src
